# Fondamentaux pour l'utilisation de R {#sec-fondamentaux}

Ressources en français :

-   [Introduction à R et au Tidyverse](https://juba.github.io/tidyverse/index.html)[@barnier2022]
-   [utilitR: documentation collaborative sur R de l'INSEE](https://www.book.utilitr.org/index.html) [@utilitr:2022]

Ressources en anglais Les bonnes ressources anglophones gratuites sont très nombreuses, très facile à trouver sur le Web. Les grands classiques est R for data science, de Grolemund et Wickham [-@grolemund2022]. On se focalise ici avec elles qui sont le plus en lien avec nos sujets.

-   [Geocomputation with R, a book on geographic data analysis, visualization and modeling](https://geocompr.robinlovelace.net/) [@lovelace2022].
-   [Mapme.biodiversity: Efficient Monitoring of Global Biodiversity Portfolios](https://mapme-initiative.github.io/mapme.biodiversity/index.html) [@görgen2022]

## Installation

On installe R et RStudio :

-   Télécharger et installer R ([page officielle proposant les installateurs et instructions d'installation](https://cloud.r-project.org/))
-   Télécharger et installer RStudio ([page officielle proposant les installateurs et instructions d'installation](https://www.rstudio.com/products/rstudio/download/#download))

> A noter : un nombre croissant d'utilisteurs utilise VS Code. C'est une alternative intéressante, pour des utilisateurs déjà confirmés :

## Import des données

En très bref :

-   Pour les fichiers excle ou csv, dans le volet "files" du panneau en bas à droite de l'interface Rstudio, cliquer sur le fichier en question et utiliser l'assistant d'import.
-   Pour les autres fichiers, se référer à l'aide ou chercher sur internet.

Voir [cette page](https://juba.github.io) pour un topo sur les imports. \[#TODO:Préciser l'url\]

## Principes élémentaires de manipulation de données en R

On se focalise ici sur quelques aspects qui peuvent être requis pour la manipulation du code et à la marge. Points à traiter :

-   \<- / =
-   %\>%
-   fonctions
-   na.rm : Les valeurs manquantes, notées NA dans R (certaines peuvent avoir pour valeur NaN). On utilise na.rm pour les éluder dans les opérations simples.
-   verbes : select, filter, mutate, group_by / summarise

Deux opérations particulière requièrent une étude plus approfondies

-   Jointures
-   Pivots
-   map
-   unnest

Un point important est relatif aux types des variables : numérique, catégorielles, textes, dates, spatiales... En général, les opérations ne peuvent concerner que des variables du même type. Les fonctions sont souvent contraignantes quant aux types des variables qu'elles prennent comme arguments.

Pour une analyse plus approfondie, voir juba.

## Produire des cartes simples avec R

## Produire des graphiques avec R
