project:
  type: book
  output-dir: docs

book:
  title: "Impact des aires protégées sur la déforestation : guide de formation pratique"
  author: "Florent Bédécarrats, Marc Bouvier, Kenneth Houngbedji; Jeanne de Montalembert et Marin Ferry"
  date: "10/3/2022"
  repo-url: https://github.com/fBedecarrats/conservation-deforestation-madagascar
  cover-image: figs/IRD_010664_ORI_small.png
  chapters:
    - 00-index.qmd
    - 00-intro.qmd
    - part: "Préparation des données"
      chapters: 
        - 01-aires_protegees.qmd
        - 02-caracteristiques_AP.qmd
        - 03-donnees_deforestation.qmd
        - 04-donnees_en_mailles.qmd
    - part: "Évaluation d'impact"
      chapters: 
        - 05-assignation_aleatoire.qmd
        - 06-matching_AP.qmd
        - 07-avant_apres.qmd
        - 08-diff_in_diff.qmd
    - part: "Ressources"
      chapters:
        - 09-bibliographie.qmd
        - 10-fondamentaux_R.qmd
    

bibliography: bibliographie.bib

format:
  html:
    theme: cosmo
    code-fold: true

execute:
  warning: false
  error: false
