project:
  type: book
  output-dir: docs

book:
  title: "Impact des aires protégées sur la déforestation : guide de formation pratique"
  author: "Florent Bédécarrats, Marc Bouvier, Kenneth Houngbedji; Jeanne de Montalembert et Marin Ferry"
  date: "10/3/2022"
  repo-url: https://github.com/fBedecarrats/conservation-deforestation-madagascar
  cover-image: figs/IRD_010664_ORI_small.png
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: true

execute:
  warning: false
  error: false
