# Préface {.unnumbered}

Ce contenu a été développé afin de servir de support pédagogique pour l'atelier "évaluation des politiques" de la session 2022 des Universités en sciences sociales Tany Vao. Les universités Tany Vao visent à dispenser une formation à la recherche de haut niveau à l'attention de doctorants et jeunes chercheurs de Madagascar et d'Afrique de l'Ouest. Après deux jours de plénières, les participants se répartissent pendant cinq jours entre quatre ateliers parallèles : socioéconomie, éthno-écologie, anthropologie et évaluation des politiques.

L'atelier "évaluation des politiques" adopte une approche axée sur l'économétrie et la science des données. Il alterne des sessions théorique et pratique. Conformément au thème phare de Tany Vao pour 2022 ("environnement et sociétés"), le cas d'étude choisi pour servir de fil rouge à ces travaux est l'impact des aires protégées sur la déforestation.

> Mise en garde : ce document est en cours de développement : il est encore incomplet et il est susceptible de contenir des erreurs. N'hésitez pas à les signaler en cliquant sur l'icône Github en haut à gauche et à créer une "Issue".

Photo en couverture : "Déforestation à Madagascar" © IRD - Bernard Moizo
